trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      az bicep build --file BicepTemplate.bicep --stdout
    displayName: 'BICEP Validation'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'myconnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create  --resource-group Bicep --template-file BicepTemplate.bicep
    displayName: 'Deploy to Azure'